### ISSUE TITLE
LOCAL_SHARED_LIBRARIES := JavaScriptCore_shared

### ISSUE THREAD

**Issue by dgu123** [ericwlange/AndroidJSCore#1]
Hello

Super example of course , i just dont understand where is located the source code of the library called 
LOCAL_SHARED_LIBRARIES := JavaScriptCore_shared

may you tell me?

Kind regards
david

**Comment by ericwlange** [comment]
Sorry, I didn't have my notifications turned on, so I didn't see this.

Note in step 4 you must set your environment variables:
NDK_MODULE_PATH to point to where you installed the JavaScriptCore libraries/includes in step 1 (e.g. /Users/Eric/workspace/AndroidModuleReleases)

You must either build JavaScriptCore in Step 1 _OR_ just untar my copy which I have included in the release.  Then point NDK_MODULE_PATH to it.

E.g.
mkdir ~/AndroidLibs
cd ~/AndroidLibs
tar zxvf JavaScriptCore-Build_20150511.tar.gz
Then point NDK_MODULE_PATH to ~/AndroidLibs

That _should_ work.
