### ISSUE TITLE
Excuse me but.Is there any way to bind a java class to js?

### ISSUE THREAD

**Issue by loveyanbei** [ericwlange/AndroidJSCore#10]
So that I can instantiate java objects through js in some situations.

**Comment by ericwlange** [comment]
Yes, you can.  Take a look at [`SharingFunctionsExample.java`](https://github.com/ericwlange/AndroidJSCore/blob/master/examples/AndroidJSCoreExample/app/src/main/java/org/liquidplayer/androidjscoreexample/SharingFunctionsExample.java) for a detailed example.  Also look at the [`JSObject` constructor](http://ericwlange.github.io/org/liquidplayer/webkit/javascriptcore/JSObject.html#JSObject(org.liquidplayer.webkit.javascriptcore.JSContext, java.lang.Class, java.lang.Class)) specifically meant for this in the javadocs.
