### ISSUE TITLE
ExceptionHandler AndroidJSCore

### ISSUE THREAD

**Issue by krudos** [ericwlange/AndroidJSCore#11]
in ios you can write

 JSContext* context = [[JSContext alloc] initWithVirtualMachine:[[JSVirtualMachine alloc] init]];
            [ context setExceptionHandler:^(JSContext *context, JSValue *value) {
                NSLog(@"%@", value);
            }];

it there a way to have ExceptionHandler in android

**Comment by ericwlange** [comment]
Hi please see this closed issue:

https://github.com/ericwlange/AndroidJSCore/issues/7

I have added the functionality in 2.1.
