### ISSUE TITLE
add to gradle

### ISSUE THREAD

**Issue by krudos** [ericwlange/AndroidJSCore#12]
it there a way to gadle download the androidjscore files automatic like in other libraries with a line like

dependencies {

compile 'com.github.ericwlange:androidjscore:2.1'
}

i have see other projects that are easier to add

**Comment by ericwlange** [comment]
Do you have a link on how to set that up?

**Comment by krudos** [comment]
i think this should help you
http://www.vandalsoftware.com/post/52468430435/publishing-an-android-library-aar-to-a-maven


here are others
https://medium.com/android-news/the-complete-guide-to-creating-an-android-library-46628b7fc879#.wfftqf3o2

https://jitpack.io

**Comment by ericwlange** [comment]
Cool thanks.  I will look into this.

**Comment by ericwlange** [comment]
The official 3.0.0 release has been added to jitpack.  Enjoy!
