### ISSUE TITLE
Error or trying to build arm64 JSC

### ISSUE THREAD

**Issue by devdeep1987** [ericwlange/AndroidJSCore#15]
I was trying to use the AndroidJSCore project to build arm64-v8a JSC with JIT enabled. However, I keep getting this error: "Can't extract gcc patch for arm64-v8a" as it is unable to unpack the gcc-arm64-linux-x86_64.tar.bz2 file located in AndroidJSCore/dist. The exact error I get is:
`/bin/tar: This does not look like a tar archive
bzip2: (stdin) is not a bzip2 file.
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
ERROR: Can't extract gcc patch for arm64-v8a`

I tried extracting the file manually but I get the same error. Would you know how to resolve this?
Also would you have any insight on how to get JIT working for armeabi-v7a. I would prefer that but am resorting to 64 bit as it crashes on launch.

**Comment by ericwlange** [comment]
I am not aware of the unpacking issue.  Let me look into it.  Just out of curiosity, have you tried to build the x86_64 version?  It also requires my home build of gcc and it has its own archive.  If that works but arm64 doesn't then there is a corruption somewhere.  If they both don't work then I will have to dig further.

JIT does not work on v7a.  I don't know why.  It builds but crashes immediately.  I am moving to a new method for building webkit (see [this project](https://github.com/ericwlange/hemroid)), but it is still a work in progress.  In fact, I am building the v7a version of webkit today with JIT enabled.  I will see if it works.  However, I am a long way off from being able to release it.

Incidentally, I also have a copy of the gcc archives in the `hemroid` project.  Try this one and see if it works any better:

https://github.com/ericwlange/hemroid/blob/master/dist/gcc-arm64-linux-x86_64.tar.bz2

**Comment by devdeep1987** [comment]
I tried both the x86_64 tar.bz2 and also the one for arm64 in the hemroid project but had the same issue. If I do a 'cat' on one of these files such as `cat gcc-arm64-linux-x86_64.tar.bz2`, I get:
`version https://git-lfs.github.com/spec/v1
oid sha256:15404f601331329518484678352ef68a3093cbc860e7c21eddbb085239d45ed2
size 27059052
`
Instead if I do a "cat" on another tar.bz2 file say the ndk that I downloaded, I get a lot of garbled stuff which probably indicates that the tar files with the gcc patches are not properly packed?

It would be great if you could look into this.

**Comment by ericwlange** [comment]
Do you have GIT LFS installed? https://git-lfs.github.com/

**Comment by devdeep1987** [comment]
No. Would I need that to resolve this?

**Comment by ericwlange** [comment]
Yes, definitely.  Those files are huge, so they are stored using LFS.

**Comment by devdeep1987** [comment]
I downloaded git lfs and ran git-lfs install so that it now says GitLFS initialized but upon running the build script, it still gives the same error. Do I need to configure GitLFS somehow to fetch those files?

**Comment by ericwlange** [comment]
That should be all you have to do.  I haven't had any problems with LFS or gotten other reports, so there is probably something on your side.  Now that LFS is installed, perhaps try re-cloning the repo and see if that makes a difference?  It shouldn't, but I am short on other ideas.

**Comment by ericwlange** [comment]
Please re-open if this problem persists after starting from scratch.
