### ISSUE TITLE
x86 and MIPS

### ISSUE THREAD

**Issue by krudos** [ericwlange/AndroidJSCore#2]
could you add x86 and MIPS in your build release?

thanks

**Comment by ericwlange** [comment]
I haven't tried to build JavaScriptCore since May.  I recall the process being painful!  Let me see if I can get those to build when I find a few hours and will update this thread.

**Comment by akirmse** [comment]
+1 on adding the other platforms---this is a nice little library and works well on ARM.

**Comment by ericwlange** [comment]
Ok, as requested, the MIPS and X86 builds have been added to the release.  Go grab it.  It is still based on an old build of webkit (May 2014), as I couldn't get the referenced instructions to work from scratch, and I had to use the repo already on my local machine.  I will work on getting that updated, but it is going to be a long slog.  Let me know if this doesn't work.
