### ISSUE TITLE
Duplicate libgnustl_shared.so error in 2.2-pre1-release

### ISSUE THREAD

**Issue by Ebmtranceboy** [ericwlange/AndroidJSCore#22]
Hi,
I have a conflict with the 2.2 pre-release:

Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgnustl_shared.so
  	File1: app/build/intermediates/exploded-aar/AndroidJSCore-2.2-pre1-release/jni
  	File2: app/build/intermediates/exploded-aar/MyApp/MyModule/unspecified/jni

I don't know if it is MyModule version of libgnustl_shared.so that is misplaced (I didn't write it) or AndroidJSCore-2.2 version of it but I had no problem with AndroidJSCore-2.1.

Ubuntu 14.04, Android Studio 2.1

**Comment by ericwlange** [comment]
It means that "MyModule" is also using libgnustl_shared.so and both it and
AndroidJSCore include the library.  I made a design decision in 2.2 to use
shared libraries instead of static ones, because it enables to me to add
greater functionality in the future.  Let me see if I can figure out how to
deal with library clashes.

**Comment by ericwlange** [comment]
Can you try the following?

In `build.gradle` of your project, replace

```
compile(name:'AndroidJSCore-2.2-pre1-release', ext:'aar')
```

with:

```
compile(name:'AndroidJSCore-2.2-pre1-release', ext:'aar') {
    exclude "libgnustl_shared.so"
}
```

You might have to add the directories, like `exclude "lib/armeabi-v7a/libgnustl_shared.so"` but I am not sure.  Can you try some combinations and see if any of them solve the issue?

See the StackOverflow discussion here: http://stackoverflow.com/questions/36700213/duplicatefileexception-error-while-building-android-apk

**Comment by Ebmtranceboy** [comment]
Thanks for the pointer. Unfortunately Gradle won't compile with exclude. I've found someone running into the same problem

[http://stackoverflow.com/questions/24314983/how-to-exclude-duplicate-c-shared-libraries-so-in-a-multi-project-android-bui](url)

but I find his solution too complicated so I'll stick to version 2.1 until I find something better.

**Comment by ericwlange** [comment]
Let me see if I can find a more elegant solution.

**Comment by ericwlange** [comment]
I think this will do what you want.  Add this to your `build.gradle`:

```java
import com.android.build.gradle.tasks.PackageApplication
task exclude_gnustl_shared(type: Delete) << {
    def files = fileTree("${buildDir}/intermediates/exploded-aar/AndroidJSCore-2.2-pre1-release/jni/") {
        include "**/libgnustl_shared.so"
    }
    files.each { it.delete() }
}
tasks.withType(PackageApplication) { pkgTask ->
    pkgTask.dependsOn exclude_gnustl_shared
}
```

Let me know if this solves the problem.

**Comment by Ebmtranceboy** [comment]
Problem solved. Thank you Eric. Do you want me to close the issue?

**Comment by ericwlange** [comment]
Glad it worked.  Actually, please leave it open.  I'd like to think through if there is a way to do this without the developer having to think about it.  At the very least, I will add it to the documentation.

**Comment by ericwlange** [comment]
This issue is now resolved for good in [3.0.1](https://jitpack.io/#ericwlange/AndroidJSCore/3.0.1).  I have compiled the main shared library against static libraries instead of having a bunch of shared ones.  You no longer need the workaround.

**Comment by AkhilPatoliya** [comment]
I have same error to my project please help me give any solution for that.

Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.

com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/librealm-jni.so
File1: C:\Users\akhil.patoliya.gradle\caches\modules-2\files-2.1\io.realm\realm-android\0.87.5\ab4e1fead1380252dad0e95658e53ea0c113e89c\realm-android-0.87.5.jar
File2: F:\Binder_svn_new\bindercanvas\build\intermediates\bundles\default\jni

#54

**Comment by ericwlange** [comment]
AndroidJSCore is deprecated. Please upgrade to LiquidCore as noted on the
front page.
