### ISSUE TITLE
JSCORE In Unit Test, Cant insatiate JSContext java.lang.UnsatisfiedLinkError: no gnustl_shared in java.library.path

### ISSUE THREAD

**Issue by dcrelling** [ericwlange/AndroidJSCore#25]
Hi

I am using the AndroidJsCore aar put it in our lib directory and almost everything works great. The problem is that while trying to insatiate the JSCore engine in unit tests using junit 4 we get the error below. 

java.lang.UnsatisfiedLinkError: no gnustl_shared in java.library.path

It looks like in a unit test context in Android Studio when the unit tests are running this shared lib can't be loaded. The error is being encountered when we try to create a new JSContext

public static void createEngine(String string)
  {
    engine = new JSContext();   -------------------> Error Here
    exportedItems = new JSObject(engine);
    setUpMethods();
    engine.evaluateScript(string);
  }

JsCore works find when we use it in a app deployed on a phone it just has problems when we try to insatiate it in a Unit Test context in android studio. Have you encountered these issues before using JSCore in unit tests?

**Comment by ericwlange** [comment]
I have not tried to use it in unit tests, so I haven't seen this.  Let me see what I can figure out.

**Comment by dcrelling** [comment]
great, thanks

**Comment by ericwlange** [comment]
So it looks like this is an issue for all native libraries.  You can't use Local Unit Tests for testing anything that has a dependency on the Android framework.  It only works for pure Java units.  Instead you have to use Instrumented Unit Tests, and those depend on using either the emulator or a device.  I found these two links to be the most useful:

https://code.google.com/p/android/issues/detail?id=199979
https://developer.android.com/studio/test/index.html
