### ISSUE TITLE
Suggestion for public remote repository builds

### ISSUE THREAD

**Issue by cirilla** [ericwlange/AndroidJSCore#26]
Hi

I'm looking forward for your official release, 
meanwhile I want to suggest you about easy way to publish your .aar file to public repository
a service called https://jitpack.io
all you need to do in order to publish using this service is to make your build to pass (your build fails now, take a look https://jitpack.io/com/github/ericwlange/AndroidJSCore/2.2-pre2/build.log)

Thanks

**Comment by ericwlange** [comment]
Looks promising, but I am skeptical that it will work for me.  AndroidJSCore depends on another project of mine, [`hemroid`](https://github.com/ericwlange/hemroid), which in turn builds shared libraries for each arch, downloaded from source repos.  The process can take over an hour from a fresh build.

**Comment by ericwlange** [comment]
Version 3.0.0 is now on jitpack.
