### ISSUE TITLE
Create new JSContext makes application busy forever

### ISSUE THREAD

**Issue by wkh237** [ericwlange/AndroidJSCore#27]
I'm using this library to make a React Native module, when I try to create a JSContext instance, the whole application just hanged.

I looks like the process stopped after executes the constructor

```java
new JSContext();
```
I've tried to put the line into a thread, but it still happens. Is there any suggestion on this ? 

Many thanks.

**Comment by ericwlange** [comment]
Are you using the latest release (3.0-pre1)?

How are you using this with React Native?

Any Dalvik logs that can give any hints?

**Comment by wkh237** [comment]
Hi @ericwlange , I'm using 3.0-pre1, I just write a module which following the instructions of [official document] (https://facebook.github.io/react-native/docs/native-modules-android.html). 

```java
@ReactMethod
  public void createJSContext(
     JSContext ctx = new JSContext(); // <-- application stucks here
  }
```

I tried to find useful informations from log, but it doesn't log anything. I've create a [sample react-native project](https://github.com/wkh237/rn-android-jsc-issue) that can reproduce this problem. If it is convenient your may clone the repository and try to run the project.

The implementation is in [this file](https://github.com/wkh237/rn-android-jsc-issue/blob/master/android/app/src/main/java/com/sample/AndroidJSCModule.java#L30-L34).

**Comment by ericwlange** [comment]
Thanks. I will take a look. I've never used it alongside React Native, so I
fear there may be a native library conflict. Have you tried to use it
without React Native?  Can you confirm that it doesn't hang when the react
SDK is not present?

**Comment by ericwlange** [comment]
This is confirmed as working in [3.0.1](https://jitpack.io/#ericwlange/AndroidJSCore/3.0.1).  BTW, you left `.show()` off the end of your `Toast.makeText()` lines.  I am not sure if you were expecting them to display or not.  In any case, I have verified that it plays nice with React Native.
