### ISSUE TITLE
Add support for jitpack.io

### ISSUE THREAD

**Issue by mikeyxkcd** [ericwlange/AndroidJSCore#29]
It would be nice if we had support, that way we wouldn't have to manually download the aar files for each new release.

The build is currently failing due to the directory structure of the files.

https://jitpack.io/#ericwlange/AndroidJSCore

https://github.com/jitpack/jitpack.io/issues/610

**Comment by mikeyxkcd** [comment]
Looking back, I can see there was previous issue with this same request #26 .

You can try adding a [jitpack.yml](https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#build-customization) file to handle all the hemroid setup.

**Comment by ericwlange** [comment]
Once I have stabilized version 3.0, I will add support for these repos as possible.

**Comment by ericwlange** [comment]
The official 3.0.0 release is available.  I have successfully added it to jitpack.

**Comment by mikeyxkcd** [comment]
Thanks a lot for doing this! Hopefully it wasn't too difficult.

How did you get it to work without installing Hemroid?

**Comment by ericwlange** [comment]
I removed the dependency and committed the shared libraries directly in the
AndroidJSCore repo.  The javascriptcore libs have been stable for a while.
