### ISSUE TITLE
Potential build issue

### ISSUE THREAD

**Issue by u3amar** [ericwlange/AndroidJSCore#32]
The package is set to "org.liquidplayer.hemroidlib" instead of "org.liquidplayer.webkit.javascriptcore" in the AndroidMainfest.xml file. Is this intentional? I had to modify the project, which I did by exploding the .aar and extracting the hemroid.jar file - this worked fine, but on some phones I got runtime exceptions of the form: 

`com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/liquidplayer/hemroidlib/BuildConfig;`

The project was able to compile and run correctly only when I changed the package name to "org.liquidplayer.webkit.javascriptcore".

**Comment by ericwlange** [comment]
No this is not intended.  It is supposed to be as you note at the end.  Will fix it.  However, I am curious that you were unable to get it to compile properly.  I have not heard of this issue before.  Are you using some freshly updated android studio packages or something?

**Comment by ericwlange** [comment]
This is now fixed in 3.0-pre2
