### ISSUE TITLE
i want to use this library for following use cases

### ISSUE THREAD

**Issue by Prashanth-Nelli** [ericwlange/AndroidJSCore#36]
i want to use this library to download web pages ,parsing html string.
which version of  javascript this library supports

**Comment by ericwlange** [comment]
`AndroidJSCore` is purely a JavaScript runtime environment.  It is not a full-blown browser and therefore does not include web features.  Downloading web pages requires access to HTTP(S) and parsing HTML requires the DOM.  Neither are part of JavaScriptCore.  Instead they are part of WebCore, which I have not ported.

In your case, this may not be the right project for you.  Have you tried just using a `WebView` and calling [`evaluateJavascript`](https://developer.android.com/reference/android/webkit/WebView.html#evaluateJavascript(java.lang.String, android.webkit.ValueCallback<java.lang.String>))?  It will be much slower than `AndroidJSCore`, but it should do what you want.

**Comment by Prashanth-Nelli** [comment]
@ericwlange thanks for the help.

I want to do fetching and parsing in the background process.
using webview in this case is not possible as webview can only be accessible in ui thread.
