### ISSUE TITLE
NodeJs Packages in AndroidJSCore

### ISSUE THREAD

**Issue by maPaydar** [ericwlange/AndroidJSCore#37]
can i use node packages in `AndroidJSCore` ?
i had some researches , in this link https://blog.risingstack.com/running-node-modules-in-your-ios-project/ used node packs in javascriptcore in swift,
i wanna implement it in `AndroidJSCore` .

**Comment by ericwlange** [comment]
Yes, you should be able to run Node packages if they have been run through `browserify`.  The `require()` function is not supported by core JavaScript, but `browserify` should solve that particular problem.  However, keep in mind that this is not a Node runtime environment (I am actually experimenting with that now), so if your package depends on things like `fs` and `process`, these won't be available.
