### ISSUE TITLE
Can I require the js module that stored in Android storage?

### ISSUE THREAD

**Issue by YjyJeff** [ericwlange/AndroidJSCore#38]
Can I require the js module that stored in Android storage? I want to use javascirpt code dynamically.

**Comment by ericwlange** [comment]
Sure.  Open the file and copy into a `String` in Java and then call
`context.evaluateScript(string)` to execute.  There is no Node-like
`require` function in core JavaScript.  You'll have to load it yourself.

**Comment by YjyJeff** [comment]
@ericwlange Thanks a lot!
