### ISSUE TITLE
Work around for JSObject slowness... JSON strings?

### ISSUE THREAD

**Issue by charles-b-stb** [ericwlange/AndroidJSCore#41]
I am attempting to use this library to load a medium amount of data (a list of some hundred objects) into memory and have found a significant slowness with setting properties for JSObjects. 

I see roughly 1 ms per property setting, which doesn't sound like much, but when you are sending a list of over 700 objects with 5 integer properties each, it take upwards of 2 seconds to load into memory.

I found a similar slowness when working with reading properties out of JSObjects and I've noticed that I can process data a lot faster when reading out of JSValues using the toJson() method which uses NDK to process the data. From there I let Android's much faster JSONObject class to take over loading values into primitives for me.

I suspect I might see a similar performance boost if I can load data back into the JS engine using a nonexistant fromJson method. I see a C++ hook in JSValue.java (i.e. makeFromJSONString) that looks like it might be able to convert to JSValues from a JSON string. Are there any plans to connect this soon?

**Comment by ericwlange** [comment]
This is already there: http://ericwlange.github.io/org/liquidplayer/webkit/javascriptcore/JSON.html

Simply: `JSValue value = JSON.parse(string)`

**Comment by charles-b-stb** [comment]
I didn't see that one, thanks. I'll try it on Monday.

:-)
