### ISSUE TITLE
App crashes when trying to pass a Java callback

### ISSUE THREAD

**Issue by kasuboski** [ericwlange/AndroidJSCore#42]
I'm trying to pass a java object for the JS to use as a callback, but when called the app crashes with:
Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI SetLongField called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object[] org.liquidplayer.webkit.javascriptcore.JSBaseArray.toArray(java.lang.Class)' on a null object reference'

Java call: 
```
JSFunction func = jsContext.property("callbackTest").toFunction();
        NetworkCallback callback = new NetworkCallback(jsContext) {
            @Override
            public void onSuccess(Object... args) {
                if(null != args[0]) {
                    Log.d(TAG, args[0].toString());
                }
            }

            @Override
            public void onError(Object... args) {
                Log.e(TAG, args[0].toString());
            }
        };

        func.call(null, callback);
```

JS:
```
function callbackTest(callback) {
    console.log('Callback Test');//I mapped this to Android Log it works
    callback.onSuccess("Hurray");//this is where the exception happens
}
```

I have NetworkCallback extending JSObject and implementing an interface. It is declared as abstract. Is this possibly the issue?

If this isn't possible is there a preferred method to get values back to Java after an asynchronous event in Javascript?

**Comment by kasuboski** [comment]
After changing the argument of the callback methods to a String it seems to work. I'm guessing there just isn't support for Object...?

**Comment by ericwlange** [comment]
It doesn't really know what to do with Object. If you want a generic type,
use JSValue.
