### ISSUE TITLE
How to access a nested JSValue?

### ISSUE THREAD

**Issue by polaski** [ericwlange/AndroidJSCore#48]
Hi I am trying to translate the following Objective-c code into Android code:

            JSValue *func = context[@"module"][@"func"];
            JSValue *val = [func callWithArguments:@[arg1, arg2]];

The problem I'm having is the first line. I have looked at all the examples and even looked into the code but couldn't figure out how to access a nested attribute (In this case `contest[@"module"][@"func"]`).

If it was just a single level attribute I could do `JSValue func = context.property("module")` but I don't know how to get the `func` in this particular case.

Sorry if this is a newbie question, but I think others may run into this question as well so thought I would ask!

**Comment by ericwlange** [comment]
JSValue func = context.property("module").toObject().property("func");

**Comment by polaski** [comment]
Thanks!
