### ISSUE TITLE
Problem  with android:supportsRtl="true"

### ISSUE THREAD

**Issue by phillippbertram** [ericwlange/AndroidJSCore#51]
Hi,

I was trying out your nice project, but it seems there is one little problem during the `AndroidManifest.xml` merge process.

Is there any reason why you set `android:supportsRtl="true"` in your `AndroidManifest.xml` file? That leads to some merge conflicts that I cannot solve, event not with `tools:replace` or simiar statements.

Thanks :)

Maybe following thread could be interesting in this case

https://android.jlelse.eu/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a#.h1przxgye

**Comment by ericwlange** [comment]
AndroidJSCore is no longer supported.  Please update to [`LiquidCore`](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-as-a-Native-Javascript-Engine) and let me know if the problem persists there.
