### ISSUE TITLE
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.

### ISSUE THREAD

**Issue by AkhilPatoliya** [ericwlange/AndroidJSCore#54]
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/librealm-jni.so
  	File1: C:\Users\akhil.patoliya\.gradle\caches\modules-2\files-2.1\io.realm\realm-android\0.87.5\ab4e1fead1380252dad0e95658e53ea0c113e89c\realm-android-0.87.5.jar
  	File2: F:\Binder_svn_new\bindercanvas\build\intermediates\bundles\default\jni

**Comment by AkhilPatoliya** [comment]
Any idea about this issues please help me or please suggest me any solution.

**Comment by ericwlange** [comment]
AndroidJSCore is deprecated. Please upgrade to LiquidCore as noted on the
front page.

**Comment by AkhilPatoliya** [comment]
Hello,
ericwlange i am little bit confused please explain more detail. my issues not solved

**Comment by AkhilPatoliya** [comment]
This is my gradle file

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

buildscript
        {
            repositories {
                maven { url 'https://maven.fabric.io/public' }
            }

            dependencies {
                classpath 'io.fabric.tools:gradle:1.+'
            }
        }
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'
    defaultConfig
            {
                applicationId "com.plusinfosys.binder"
                minSdkVersion 19
                targetSdkVersion 25
                versionCode 1
                versionName "1.0"
                multiDexEnabled true
                testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
/*
                jackOptions {
                    enabled true
                }*/


            }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
           proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    repositories {
        jcenter()

    }

 /*   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
     //   incremental false
    }*/
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.1.1'
    //  compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    compile('com.twitter.sdk.android:tweet-composer:3.0.0@aar') {
        transitive = true;
    }
    compile 'com.google.firebase:firebase-core:9.6.1'
    compile 'com.twitter.sdk.android:twitter-core:3.0.0'
    compile 'com.twitter.sdk.android:tweet-ui:3.0.0'
    compile 'com.twitter.sdk.android:tweet-composer:3.0.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.firebase:firebase-messaging:9.6.1'
    compile 'com.google.firebase:firebase-crash:9.6.1'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.roughike:bottom-bar:2.1.1'
    compile 'id.zelory:compressor:1.0.4'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.facebook.android:facebook-android-sdk:4.10.1'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support:support-annotations:25.1.1'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.0'
    compile 'com.github.pwittchen:gesture:0.0.1'
    compile project(':library')
    compile project(':tooltioLib')
    compile project(':bindercanvas')
    compile 'com.google.android.gms:play-services-appindexing:9.6.1'
    compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'
    compile project(':linkedin-sdk')
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.google.firebase:firebase-core:9.6.1'
    compile 'uk.co.jakelee:vidsta:1.0.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.1@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:crashlytics-ndk:1.1.2@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:answers:1.4.1@aar') {
        transitive = true;
    }
    compile files('libs/fmmr.jar')

}
apply plugin: 'com.google.gms.google-services'

**Comment by AkhilPatoliya** [comment]
This is my build.gradle code


apply plugin: 'com.android.library'
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'
    testCompile 'junit:junit:4.12'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.github.lassana:continuous-audiorecorder:1.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.github.zomato:androidphotofilters:1.0.1'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'id.zelory:compressor:1.0.4'
    compile 'com.google.code.gson:gson:2.6.1'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.writingminds:FFmpegAndroid:0.3.2'
    compile 'io.realm:realm-android:0.87.5'
    compile 'com.android.support:exifinterface:25.1.0'
    compile 'io.reactivex:rxjava:1.1.9'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'
}

**Comment by ericwlange** [comment]
I'm not sure I understand your confusion.  This project, AndroidJSCore, is no longer supported.  The last edit was made to it over a year ago.  Please go to the [`LiquidCore`](https://github.com/LiquidPlayer/LiquidCore) project and use that instead.  It works (almost) exactly the same, as described [here](https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-as-a-Native-Javascript-Engine).  This is very clearly explained in **bold lettering** on the front page of this project:

**AndroidJSCore is currently unsupported.  Instead, I am moving all of this functionality and more to its permanent home, [LiquidCore](https://github.com/LiquidPlayer/LiquidCore).  Please migrate to this version going forward.**

AndroidJSCore is buggy and old.  Don't use it.

**Comment by AkhilPatoliya** [comment]
You are right but i am not use your project actually my issue is totally different and i am used relam and my issue regarding realm api which i used in my project.

compile 'io.realm:realm-android:0.87.5'

**Comment by AkhilPatoliya** [comment]
This realm api generate an error of Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug' .
so i ask you about this error. and yes i use android studio 3.0.1 Canary

**Comment by ericwlange** [comment]
I really don't understand why you are asking me about something that is completely unrelated to this project?  May I suggest stackoverflow?
