### ISSUE TITLE
How to pass Custom Java object to AndroidJSCore

### ISSUE THREAD

**Issue by kashifgrocerkey** [ericwlange/AndroidJSCore#55]
Hi I have a class Person as:

`Person { 
@JsonProperty("Name")
String name;

@JsonProperty("Age")
int age;
}`

I want to pass this into AndroidJSCore but i got exception unknown property 'Name' from underlying js function. But if  i covert my 'Person' object into Map/HashMap using 'ObjectMapper' and then pass it to AndroidJSCore then it works fine but it has performance issues.

Please suggest any good way to pass Custom Java objects as well as List of<Person> to AndroidJSCore

**Comment by ericwlange** [comment]
`AndroidJSCore` is ancient and deprecated.  Please use [`LiquidCore`](https://github.com/LiquidPlayer/LiquidCore) instead.

**Comment by kashifgrocerkey** [comment]
Yes i have used both libraries, i am using com.github.LiquidPlayer:LiquidCore:0.5.0 . Can you please suggest any good way to pass Custom Java objects as well as List of to LiquidCore
