### ISSUE TITLE
How to call a JavaScript function

### ISSUE THREAD

**Issue by aexmachina** [ericwlange/AndroidJSCore#8]
Sorry if I'm being dense, but how do I call a JavaScript function on an JavaScript object? Do I need to assign it to a global variable and use `evaluateScript()`?

**Comment by ericwlange** [comment]
That's one way to do it.  You can also pass it as an argument to callAsFunction:

    String script = "function(x) { return x + 1; };";
    JSObject func = context.evaluateScript(script);
    JSValue myValue = new JSValue(context,100);
    JSValue [] args = {myValue}; 
    JSValue newValue = func.callAsFunction(null,args); // newValue = 101

Of course, you can pass a JSObject just as easily, as it is a subclass of JSValue.

**Comment by aexmachina** [comment]
`context.evaluateScript` returns a `JSValue`, not a `JSObject` though. I tried to cast it, but it doesn't work.

**Comment by ericwlange** [comment]
Sorry, yes that's what I get for writing code without testing it.  Try:

    JSObject func = context.evaluateScript(script).toObject();

which will convert a value to an object, if it is an object.  Otherwise it will throw a JSException.  You can also test using value.isObject().

**Comment by aexmachina** [comment]
Yep, thanks.

**Comment by ericwlange** [comment]
By the way, there is another way to do it, if your goal is to be as quick-and-dirty as possible.  You can use a special [JSObject constructor](http://ericwlange.github.io/org/liquidplayer/webkit/javascriptcore/JSObject.html#JSObject(org.liquidplayer.webkit.javascriptcore.JSContext, java.lang.String, java.lang.String[], java.lang.String, java.lang.String, int)):

```java
JSObject incrementFunction = new JSObject(
    context,
    "incr", // name of the function
    new String[]{"x"}, // array of parameter names
    "return x+1;" // body of function
);

JSValue five = incrementFunction.callAsFunction(null, new JSValue[]{ 4 });
```

**Comment by VishalKumar2016** [comment]
I am trying to load a JS file as JSContext and want to call it's function is there anyway with updated version.

**Comment by ericwlange** [comment]
```java
File file = new File("/my/js/file.js");
JSContext context = new JSContext();

byte[] bytes = new byte[file.length()];
FileInputStream in = new FileInputStream(file);
try {
    in.read(bytes);
    context.evaluateScript(new String[bytes]);
} finally {
    in.close();
}
```

**Comment by NitishAgrawal** [comment]
I have used this code in android with some changes. 
            JSContext context = new JSContext();

            AssetFileDescriptor fileDescriptor = getAssets().openFd("demo.js");
            FileInputStream stream = fileDescriptor.createInputStream();

            InputStream is=getAssets().open("demo.js");
            byte[] bytes=new byte[is.available()];
            try {
                stream.read(bytes);
                context.evaluateScript(new String[bytes]);
            } finally {
                stream.close();
                is.close();
            }

But compiler is showing message in below line 
context.evaluateScript(new String[bytes]); 
that new String[bytes] require int not bytes.

**Comment by ericwlange** [comment]
Error above.  Should be `new String(bytes)` not `new String[bytes]`.  My mistake.  I didn't test it.

**Comment by NitishAgrawal** [comment]
Hi Ericwlange,
I have a bundle file created by React-JS with some libraries now I want to use this in Android. This bundle.js has multiple methods how can I call these methods from Android and then get a response in Android.

**Comment by ericwlange** [comment]
```java
// code above -- evaluate the script
// assume you want to call, in JavaScript, MyObjectName.myFunctionName(arg1, arg2, ...)
JSFunction func = context.property("MyObjectName").toObject()
    .property("myFunctionName").toObject().toFunction();
JSValue result = func.call(null /* or 'this' object if you have one */, arg1, arg2, ...);
```

Please see the Javadocs for API reference.

**Comment by NitishAgrawal** [comment]
But code 
JSContext context = new JSContext();
            InputStream is=getAssets().open("bundle.js");
            byte[] bytes=new byte[is.available()];
            try {
                context.evaluateScript(new String(bytes));
            } finally {
                is.close();
            }

Giving Error "Invalid character: '\0'" 

and if use full code

 JSContext context = new JSContext();
            AssetFileDescriptor fileDescriptor = getAssets().openFd("bundle.js");
            FileInputStream stream = fileDescriptor.createInputStream();

            InputStream is=getAssets().open("bundle.js");
            byte[] bytes=new byte[is.available()];
            try {
                stream.read(bytes);
                context.evaluateScript(new String(bytes));
                // JSObject func = context.evaluateScript('sdk').toObject();
            } finally {
                stream.close();
                is.close();
            }

Its giving error "java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed"

But my file is a JS file.

**Comment by NitishAgrawal** [comment]
Thanks for your help now I am able to evaluate script by below code 
try {
            JSContext context = new JSContext();
            InputStream is=getAssets().open("bundle.js");
            try {
                context.evaluateScript(convertStreamToString(is));
                JSObject sdk = context.property("myObjectName").toObject();
                JSValue genMne = sdk.property("myFunctionName");
                JSFunction func = genMne.toObject().toFunction();
                JSValue result = func.call(null );
            } finally {
                is.close();
            }

**Comment by ericwlange** [comment]
I can't debug this without seeing the JS.
